############################
## CHANGE THESE
############################

baseURL: 'https://lsburton.com'
title: 'Luke Burton'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
